- hosts: all
  sudo: true
  tasks:

    - apt_key: url=http://opensource.wandisco.com/wandisco-debian.gpg state=present
    - apt_repository: repo='deb http://opensource.wandisco.com/ubuntu trusty svn18' state=present
    - apt: name={{item}} state=present
      with_items:
        - trac
        - subversion
        - apache2
        - libapache2-mod-wsgi
        - libapache2-svn
        - apache2-utils
        - python-pip
        - git
        - emacs23-nox
    # http://trac.edgewall.org/ticket/11345
    - apt: name={{item}} state=absent
      with_items:
        - python-babel
        - python-babel-localedata
    - name: create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=XX/ST=XX/L=XXX/O=vagrant/CN=localhost" -days 3650 -keyout /etc/ssl/private/vagrant.key -out /etc/ssl/certs/vagrant.pem creates=/etc/ssl/certs/vagrant.key
      register: openssl
    - command: cp -a /etc/ssl/certs/vagrant.pem /vagrant/vagrant.pem
      when: openssl | changed
    - file: path={{item}} state=directory owner=www-data
      with_items:
        - /var/local/trac
        - /var/local/svn
    - command: svnadmin create /var/local/svn creates=/var/local/svn/format
      sudo_user: www-data      
    - command: trac-admin /var/local/trac initenv project sqlite:db/trac.db svn /var/local/svn creates=/var/local/trac/VERSION
      sudo_user: www-data
      register: initenv
    - command: htpasswd -bc /var/local/trac/.htpasswd admin admin creates=/var/local/trac/.htpasswd
    - command: trac-admin /var/local/trac permission add admin TRAC_ADMIN
      sudo_user: www-data
      when: initenv | changed
    - command: trac-admin /var/local/trac config set logging log_type file
      sudo_user: www-data
      when: initenv | changed
    - copy: src=trac.wsgi dest=/var/local/trac/trac.wsgi
      notify: restart apache2
      when: initenv | changed
    - command: trac-admin /var/local/trac config set components tracopt.versioncontrol.svn.* enabled
      sudo_user: www-data
      notify: restart apache2
      when: initenv | changed
    - file: path={{item}} state=absent
      with_items:
        - /etc/apache2/sites-enabled/000-default.conf
        - /etc/apache2/sites-available/000-default.conf
        - /etc/apache2/sites-available/default-ssl.conf
      notify: restart apache2
    - copy: src=apache-trac.conf dest=/etc/apache2/sites-available/trac.conf
      notify: restart apache2
    - command: a2ensite trac.conf creates=/etc/apache2/sites-enabled/trac.conf
      notify: restart apache2
    - command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.conf
      notify: restart apache2
    - command: a2enmod dump_io creates=/etc/apache2/mods-enabled/dump_io.conf
      notify: restart apache2
    - command: svn checkout file:///var/local/svn /tmp/svn-checkout creates=/tmp/svn-checkout
    - copy: src=sample_document.docx dest=/tmp/svn-checkout/
      register: sample_document
    - command: svn add /tmp/svn-checkout/sample_document.docx
      when: sample_document | changed
    - command: svn ci -m "store document" /tmp/svn-checkout/
      when: sample_document | changed
    - command: pip install git+https://github.com/CGI-define-and-primeportal/trac-plugin-contextmenuplugin.git creates=/usr/local/lib/python2.7/dist-packages/contextmenu/
      register: contextmenuplugin
      notify: restart apache2
    - command: trac-admin /var/local/trac config set components contextmenu.* enabled
      sudo_user: www-data
      when: contextmenuplugin | changed
    - command: trac-admin /var/local/trac config set svn repository_url https://localhost:10443/svn/
      sudo_user: www-data
      when: contextmenuplugin | changed
    - command: python setup.py develop chdir=/vagrant creates=/usr/local/lib/python2.7/dist-packages/TracSharePointInteroperability.egg-link
      register: tracsharepoint
      notify: restart apache2
    - command: trac-admin /var/local/trac config set components tracsharepoint.* enabled
      sudo_user: www-data
      when: tracsharepoint | changed
      
  handlers:
      - name: restart apache2
        service: name=apache2 state=reloaded enabled=yes
